"""Commanding a battle in person.

    the player opens a battle and presses "Command the battle" ─► the game
        pauses and the bridge sends the field as it stands (both sides, the
        wings and the reserves, the men, the commanders, the ground)
    the side panel opens on it: a narrator outside the battle sets the scene
        with the true numbers, and the ruler gives the plan in their own words
    the plan is judged against the field ─► small bonuses or penalties land on
        the armies there, and the game runs again at the slowest speed
    while it runs the bridge reports the field every second or so; at the
        moments that matter (the first clash, a wing giving way, a long grind,
        the edge of a rout) the game pauses and a moment of the battle comes
        up: three orders whose effect nobody knows yet, or the ruler's own
    the choice is rolled at once and applied, the game runs on, and how it
        went is told by the next moment - or by the account of the battle
        when it ends

Everything the game is told goes through the mod's own effects
(in_game/common/scripted_effects/votc_battle_effects.txt, generated by
tools/gen_battle.py from LEVERS below), so the AI never writes script.
"""

from __future__ import annotations

import random
import re
import time
from dataclasses import dataclass, field
from typing import Any

from . import gamedate, prompts
from .drawer import Header
from .mailbox import with_gist
from .ai import AIError
from .protocol import Record

# ----------------------------------------------------------------------------
# What can change on the field. Each lever is a family of unit modifiers, in
# three strengths each way. The names are what the player sees on the army's
# tooltip once the order has been given - never before.
# ----------------------------------------------------------------------------
_P = (0.05, 0.10, 0.20)
LEVERS: dict[str, tuple[str, str, list[tuple[str, tuple]]]] = {
    "morale": ("Heart in the ranks", "Heart gone from the ranks", [("land_morale_modifier", _P)]),
    "discipline": ("Ranks kept tight", "Ranks come loose", [("discipline", (0.025, 0.05, 0.10))]),
    "command": ("The field well read", "The field misread", [("commander_combat_bonus", (1, 2, 3))]),
    "cavalry": ("The horse well used", "The horse thrown away",
                [("army_light_cavalry_power", _P), ("army_heavy_cavalry_power", _P)]),
    "infantry": ("The foot well placed", "The foot badly placed",
                 [("army_light_infantry_power", _P), ("army_heavy_infantry_power", _P)]),
    "artillery": ("The guns well sited", "The guns badly sited", [("army_artillery_power", _P)]),
}
# Blows struck at once, as fractions: morale knocked out of a side, men lost,
# morale given back (absolute, as the game's add_morale takes it).
SHAKE = (0.05, 0.12, 0.25)
BLEED = (0.02, 0.05, 0.10)
RALLY = (0.1, 0.2, 0.4)
OWN_DAYS, FOE_DAYS = 20, 12

# How hard the field is, per difficulty: the strongest good effect a plan can
# earn, the worst a mistake can cost, how luck leans, how dangerous the front is.
DIFF = {
    "easy": {"up": 3, "down": 2, "luck": 10, "risk": 0.5},
    "normal": {"up": 2, "down": 3, "luck": 0, "risk": 1.0},
    "hard": {"up": 2, "down": 3, "luck": -8, "risk": 1.3},
    "very_hard": {"up": 1, "down": 3, "luck": -15, "risk": 1.6},
}
WOUND = (0.0, 0.04, 0.10, 0.20)          # chance of a wound, by how exposed the ruler was (0-3)
FALL = (0.0, 0.005, 0.015, 0.04)         # chance of death, the same

MAX_MOMENTS = 5


def modifier_key(lever: str, up: bool, level: int) -> str:
    return f"votc_bm_{lever}_{'up' if up else 'down'}{level}"


def all_modifiers():
    """(key, shown name, [(modifier type, value)]) for every modifier the mod defines."""
    for lever, (good, bad, parts) in LEVERS.items():
        for up in (True, False):
            for level in (1, 2, 3):
                vals = [(t, v[level - 1] if up else -v[level - 1]) for t, v in parts]
                yield modifier_key(lever, up, level), (good if up else bad) + " " + "I" * level, vals


# ----------------------------------------------------------------------------
# Reading the field
# ----------------------------------------------------------------------------
_NUM = re.compile(r"-?\d[\d,.]*\s*[kKmM]?")


def _num(raw: str | None) -> float | None:
    """'12,400' '12.4K' '0.62' '62%' -> a number; None when unresolved or empty."""
    if raw is None:
        return None
    text = str(raw).strip()
    if not text or "[" in text:
        return None
    m = _NUM.search(text.replace(" ", ""))
    if not m:
        return None
    tok = m.group(0).replace(" ", "")
    mult = 1.0
    if tok[-1] in "kK":
        mult, tok = 1000.0, tok[:-1]
    elif tok[-1] in "mM":
        mult, tok = 1_000_000.0, tok[:-1]
    if "," in tok and "." in tok:
        tok = tok.replace(",", "")
    elif "," in tok:
        # "12,400" thousands; "0,62" a decimal comma
        head, _, tail = tok.partition(",")
        tok = tok.replace(",", "") if len(tail) == 3 else head + "." + tail
    try:
        value = float(tok) * mult
    except ValueError:
        return None
    if text.endswith("%"):
        value /= 100.0
    return value


def _frac(raw: str | None) -> float | None:
    """A morale reading as 0..1, whether the game wrote 0.62 or 62."""
    v = _num(raw)
    if v is None:
        return None
    return v / 100.0 if v > 1.5 else v


def _text(raw: str | None) -> str:
    text = (raw or "").strip()
    return "" if "[" in text else text


@dataclass
class Side:
    tag: str = ""
    country: str = ""
    player: bool = False
    commander: str = ""
    mil: float | None = None
    morale: float | None = None          # 0..1 of the side's full morale
    men: float | None = None             # men in the fighting line
    visual: float | None = None          # all men on the field
    losses: float | None = None
    prisoners: float | None = None
    dice: float | None = None
    left: float | None = None
    center: float | None = None
    right: float | None = None
    left_m: float | None = None
    center_m: float | None = None
    right_m: float | None = None
    reserve: float | None = None

    @classmethod
    def of(cls, rec: Record) -> "Side":
        f = rec.fields
        return cls(
            tag=_text(f.get("tag")), country=_text(f.get("country")), player=_text(f.get("player")) == "1",
            commander=_text(f.get("cmd")), mil=_num(f.get("mil")), morale=_frac(f.get("morale")),
            men=_num(f.get("men")), visual=_num(f.get("all")), losses=_num(f.get("losses")),
            prisoners=_num(f.get("prisoners")), dice=_num(f.get("dice")),
            left=_num(f.get("left")), center=_num(f.get("center")), right=_num(f.get("right")),
            left_m=_frac(f.get("leftm")), center_m=_frac(f.get("centerm")), right_m=_frac(f.get("rightm")),
            reserve=_num(f.get("reserve")),
        )

    def total(self) -> float:
        return (self.visual if self.visual is not None else (self.men or 0) + (self.reserve or 0)) or 0


@dataclass
class Field:
    name: str = ""
    date: str = ""
    active: bool = True
    naval: bool = False
    bombard: bool = False
    frontage: float | None = None
    place: str = ""
    province: str = ""
    topography: str = ""
    vegetation: str = ""
    climate: str = ""
    river: bool = False
    owner: str = ""
    gone: bool = False                   # the bridge found no battle there any more
    att: Side = field(default_factory=Side)
    dfn: Side = field(default_factory=Side)
    census: dict[str, float] = field(default_factory=dict)
    raw: list[str] = field(default_factory=list)

    @property
    def valid(self) -> bool:
        return bool(self.place) and self.active and (self.att.men is not None or self.dfn.men is not None)

    def sides(self, ours: str) -> tuple[Side, Side]:
        return (self.att, self.dfn) if ours == "att" else (self.dfn, self.att)


class _Reading:
    """The records of one report of the field, as they come in."""

    def __init__(self) -> None:
        self.field = Field()

    def feed(self, rec: Record) -> None:
        f = rec.fields
        if rec.kind == "BATTLE":
            self.field = Field(
                name=_text(f.get("name")), date=_text(f.get("date")), active=_text(f.get("active")) != "0",
                naval=_text(f.get("naval")) == "1", bombard=_text(f.get("bombard")) == "1",
                frontage=_num(f.get("frontage")), place=_text(f.get("loc")), province=_text(f.get("province")),
                topography=_text(f.get("topo")), vegetation=_text(f.get("veg")), climate=_text(f.get("climate")),
                river=_text(f.get("river")) == "1", owner=_text(f.get("owner")),
                gone=_text(f.get("gone")) == "1")
        elif rec.kind == "BSIDE":
            side = Side.of(rec)
            if rec.at(0) == "att":
                self.field.att = side
            else:
                self.field.dfn = side
        elif rec.kind == "BCENSUS":
            self.field.census = {k: v for k, v in ((k, _num(x)) for k, x in f.items()) if v is not None}
        self.field.raw.append(rec.raw[:400])


def _short(text: str, limit: int) -> str:
    """A line cut at a word, never mid-word; labels such as 'Cautious plan:' dropped."""
    text = re.sub(r"^\s*[\w' ]{3,24}:\s+", "", text.strip()) if re.match(r"^\s*[\w' ]{3,24}:\s+\S", text) else text.strip()
    if len(text) <= limit:
        return text
    cut = text[:limit].rsplit(" ", 1)[0].rstrip(",;:")
    return cut + "…"


def _hours(date: str) -> int:
    """Hours since year 0, for a date the bridge wrote ('08:00, 1 April, 1337')."""
    p = gamedate.parse(date)
    if p is None:
        return 0
    hour = re.search(r"\b(\d{1,2}):\d{2}\b", date or "")
    return ((p[0] * 365 + p[1] * 30 + p[2]) * 24) + (int(hour.group(1)) if hour else 0)


def _men(v: float | None) -> str:
    if v is None:
        return "unknown"
    return f"{int(round(v)):,}"


def _morale_words(v: float | None) -> str:
    if v is None:
        return "unknown"
    for limit, words in ((0.12, "breaking - men already running"), (0.3, "badly shaken"),
                         (0.5, "worn and uncertain"), (0.7, "holding, but tiring"), (0.9, "firm"),
                         (9.0, "fresh and eager")):
        if v <= limit:
            return words
    return "fresh"


def _width_words(frontage: float | None, men: float) -> str:
    """How much of an army the ground lets fight at once - in words."""
    if not frontage:
        return "unknown"
    room = frontage * 1000                 # a company is about a thousand men at full strength
    if men and men > room * 1.3:
        return "narrow for armies this size: many must wait their turn behind the fighting line"
    if frontage <= 12:
        return "narrow ground: the lines cannot spread far"
    if frontage <= 24:
        return "room enough for both lines to deploy"
    return "wide open ground, where a longer line can wrap around a shorter one"


def _skill_words(v: float | None) -> str:
    if v is None:
        return ""
    v = v if v > 10 else v * 10          # abilities are 0-100; old saves may say 0-10
    for limit, words in ((20, "a poor general"), (40, "a middling general"), (60, "a capable general"),
                         (80, "a very able general"), (101, "a brilliant general")):
        if v < limit:
            return words
    return ""


# ----------------------------------------------------------------------------
# Prompts
# ----------------------------------------------------------------------------
# How battles are told: prompts.text("battle_narrator"), editable by the player.

LEVER_TEXT = """
WHAT ORDERS CAN TOUCH (effects; the game applies them to the armies there):
- lever effects, on "ours" or "theirs", "up" (better) or "down" (worse), level 1-3
  (1 a nudge, 2 clear, 3 decisive - rare):
  morale (the men's heart and staying power), discipline (drill, order in the
  ranks), command (the general's grip on the field: better or worse fortune in
  every clash), cavalry, infantry, artillery (how well that arm is used)
- blows struck at once: "shake" (morale knocked out of a side), "bleed" (men
  lost), "rally" (heart given back; ours only), level 1-3.
Be honest. A good plan for THIS field earns something; a plan that ignores the
ground, the numbers or the enemy costs something. Most orders do a little of
both. Nothing is free: a bold stroke that works usually costs men too.
""".strip()

EFFECT_SCHEMA = {
    "type": "object",
    "additionalProperties": False,
    "required": ["kind", "side", "direction", "level"],
    "properties": {
        "kind": {"type": "string", "enum": ["morale", "discipline", "command", "cavalry", "infantry", "artillery",
                                            "shake", "bleed", "rally"]},
        "side": {"type": "string", "enum": ["ours", "theirs"]},
        "direction": {"type": "string", "enum": ["up", "down"],
                      "description": "For shake/bleed/rally: 'up' - the blow lands as named."},
        "level": {"type": "integer", "minimum": 1, "maximum": 3},
    },
}

BRIEF_SCHEMA = {
    "type": "object",
    "additionalProperties": False,
    "required": ["title", "briefing", "plans"],
    "properties": {
        "title": {"type": "string", "description": "The battle's name as it would be remembered, e.g. 'The Battle of "
                                                   "[place]'. Max 60 characters."},
        "briefing": {"type": "string", "description": "280-450 words. The field before the orders."},
        "plans": {"type": "array", "minItems": 3, "maxItems": 3,
                  "items": {"type": "string", "description": "A possible plan, as the ruler might say it: first "
                                                             "person, concrete, max 110 characters."}},
    },
}

BRIEF_TASK = """
{style}

THE FIELD, AS IT STANDS (the only truth: never contradict a number):
{field}

{setting}

{war}

<<GUIDE>>
{ruler}
The ruler's plan has not been given yet: nothing has been ordered.
Write everything the player reads in {lang}.
{player}
""".strip()

PLAN_SCHEMA = {
    "type": "object",
    "additionalProperties": False,
    "required": ["judgement", "soundness", "effects", "personal_risk", "summary", "watch", "reading"],
    "properties": {
        "judgement": {"type": "string", "description": "In English, hidden from the ruler, 2-4 sentences: what is "
                                                       "sound and what is unsound in this order, on THIS field."},
        "soundness": {"type": "integer", "minimum": 0, "maximum": 10,
                      "description": "How good this order is for THIS field, as a great commander would judge: "
                                     "the ground, the numbers, the enemy, the troops, the general's ability to "
                                     "carry it out. 5 is ordinary."},
        "effects": {"type": "array", "maxItems": 3, "items": EFFECT_SCHEMA},
        "personal_risk": {"type": "integer", "minimum": 0, "maximum": 3,
                          "description": "How far the ruler puts their own body in danger with this order: 0 not "
                                         "at all, 1 close to the fighting, 2 in it, 3 leading a charge. Only if the "
                                         "ruler is on the field."},
        "summary": {"type": "string", "description": "In English, one line: what the order is."},
        "watch": {"type": "string", "description": "In English, hidden: where this order is weak, and what would "
                                                   "make it pay off - for the moments to come."},
        "reading": {"type": "string", "description": "60-140 words, a SCENE, not a judgement: the order carried to "
                                                     "the officers, how each takes it (a nod, a doubt said aloud, "
                                                     "a curse), the first movements it sets off. It must not say "
                                                     "whether the order is good or bad, nor weigh its risks, nor "
                                                     "restate the numbers: that shows later, on the field."},
    },
}

PLAN_TASK = """
{style}

THE FIELD NOW:
{field}

{setting}

{so_far}

THE RULER'S {what}: "{order}"

<<GUIDE>>
(The judgement goes in "judgement"; the scene in "reading".)
{levers}
{ruler}
{difficulty}
Write "reading" in {lang}; "summary" and "watch" in English.
""".strip()

OUTCOME_SCHEMA = {
    "type": "object",
    "additionalProperties": False,
    "required": ["effects", "note"],
    "properties": {
        "effects": {"type": "array", "maxItems": 3, "items": EFFECT_SCHEMA},
        "note": {"type": "string", "description": "In English, 1-2 sentences: what happens on the field in this "
                                                 "case - to be told in the next moment."},
    },
}

MOMENT_SCHEMA = {
    "type": "object",
    "additionalProperties": False,
    "required": ["title", "body", "gist", "options"],
    "properties": {
        "title": {"type": "string", "description": "Max 60 characters."},
        "body": {"type": "string", "description": "140-260 words: this moment of the battle."},
        "gist": prompts.gist(" on the field, and what the ruler must now order"),
        "options": {
            "type": "array", "minItems": 3, "maxItems": 3,
            "items": {
                "type": "object",
                "additionalProperties": False,
                "required": ["label", "chance", "personal_risk", "success", "failure"],
                "properties": {
                    "label": {"type": "string", "description": "The order, as the ruler would give it: first "
                                                               "person, concrete, max 90 characters, no outcome."},
                    "chance": {"type": "integer", "minimum": 5, "maximum": 95,
                               "description": "Honest chance it works on THIS field, with THIS general."},
                    "personal_risk": {"type": "integer", "minimum": 0, "maximum": 3},
                    "success": OUTCOME_SCHEMA,
                    "failure": OUTCOME_SCHEMA,
                },
            },
        },
    },
}

MOMENT_TASK = """
{style}

THE FIELD NOW ({hours}):
{field}

HOW IT HAS MOVED SINCE THE LAST REPORT:
{moved}

{setting}

{so_far}

{reveal}

THIS MOMENT: {focus} {reveal_rule}
<<GUIDE>>
{levers}
{ruler}
{difficulty}
Write title, body and labels in {lang}; the notes in English.
{player}
""".strip()

AFTER_SCHEMA = {
    "type": "object",
    "additionalProperties": False,
    "required": ["title", "body", "gist", "memory_note"],
    "properties": {
        "title": {"type": "string", "description": "Max 60 characters."},
        "body": {"type": "string", "description": "220-380 words."},
        "gist": prompts.gist(": who won, at what cost"),
        "memory_note": {"type": "string", "description": "In English, 1-2 sentences for the court's memory: where, "
                                                        "against whom, who won, the losses, what the ruler did."},
    },
}

AFTER_TASK = """
{style}

THE BATTLE IS OVER. {result}

AT THE START:
{first}

THE LAST REPORT BEFORE IT ENDED:
{last}

{so_far}

{reveal}

<<GUIDE>>
(What the ruler's orders did: {reveal_rule_short}.)
Write title and body in {lang}; memory_note in English.
{player}
""".strip()


# ----------------------------------------------------------------------------
class BattleCommand:
    """One battle at a time, commanded by the player through Court Brain."""

    STALE_S = 5.0            # no report of the field for this long: the report loop is kicked

    def __init__(self, brain: Any) -> None:
        self.b = brain
        self._reading = _Reading()
        self.reset()
        self._stray_at = 0.0

    def reset(self) -> None:
        self.live = False
        self.ours = "att"
        self.first: Field | None = None
        self.field: Field | None = None          # the last good reading
        self.last_beat: Field | None = None
        self.title = ""
        self.briefing = ""
        self.plan: dict[str, Any] = {}
        self.moments: list[dict[str, Any]] = []
        self.orders: list[str] = []              # what the ruler ordered, and how it went, in English
        self.reveal: list[str] = []              # how the last orders went, not yet told
        self.waiting = ""                        # brief | plan | choice | order | moment | end
        self.last_ping = 0.0
        self.bad_readings = 0
        self.ruler_on_field = False
        self.session = None
        self.snap = None
        self.over = False                        # the field reports say the battle has ended

    # ------------------------------------------------------------ the records
    def feed(self, rec: Record) -> None:
        if rec.kind == "BATTLE":
            self._reading = _Reading()
        self._reading.feed(rec)

    def commit(self) -> Field:
        fld = self._reading.field
        self._reading = _Reading()
        return fld

    def on_report(self, fld: Field) -> None:
        """A report of the field while the time runs (every second or so)."""
        self.last_ping = time.time()
        if not self.live:
            # The game still reports a battle nobody commands here (Court Brain was
            # restarted, a save was loaded): stop it, at most once a few seconds.
            if time.time() - self._stray_at > 6:
                self._stray_at = time.time()
                self.b.mail.send(["votc_battle_end = yes"], label="battle:stray")
            return
        if fld.valid:
            self.bad_readings = 0
            self.field = fld
        else:
            self.bad_readings += 1
        if fld.gone or self.bad_readings >= 2 or (not fld.active and fld.place):
            self.over = True
        if self.waiting:
            return
        if self.over:
            self.waiting = "end"
            self.b._submit(self._finish)
            return
        if fld.valid and self._moment_due(fld):
            self.waiting = "moment"
            self.b.mail.send(["votc_battle_hold = yes"], label="battle:hold")
            self.b._submit(lambda: self._moment(fld))

    def tick(self) -> None:
        """From the main loop: a report loop that went quiet is started again."""
        if self.live and not self.waiting and self.last_ping and time.time() - self.last_ping > self.STALE_S:
            self.last_ping = time.time()
            self.b.mail.send(["votc_battle_kick = yes"], label="battle:kick")

    # ------------------------------------------------------------- beginning
    def begin(self, snap: Any, fld: Field) -> None:
        """The player pressed "Command the battle": the game is paused, the field is here."""
        if self.live:
            self.b.log("A battle was still being commanded: it is left to its generals.")
        self.reset()
        if not fld.valid or fld.naval:
            self.b.mail.send(["votc_battle_end = yes", "votc_battle_go = yes"], label="battle:none")
            self.b.log("Command the battle: " + ("sea battles are fought by the admirals." if fld.naval
                                                 else "there is no battle there any more."))
            return
        self.live, self.snap, self.first, self.field, self.last_beat = True, snap, fld, fld, fld
        self.last_ping = time.time()
        self.ours = self._our_side(snap, fld)
        us, them = fld.sides(self.ours)
        ruler = snap.ruler.name if snap.ruler and snap.ruler.name else ""
        self.ruler_on_field = bool(ruler and us.commander and (us.commander in ruler or ruler in us.commander))
        self.title = fld.name or f"The battle at {fld.place}"
        header = Header("Battle", self.title, f"{us.country or snap.name} against {them.country} · {fld.place}")
        self.b.session = None
        from .app import Session                      # the panel's session, as for every scene
        self.session = Session(kind="battle", snap=snap, header=header)
        self.b.session = self.session
        self.b._ui("open", header)
        self.b._ui("set_busy", "The field is surveyed…")
        self.waiting = "brief"
        self.b.log(f"[Battle] {self.title}: {us.country} ({_men(us.total())}) against {them.country} "
                   f"({_men(them.total())}), {'the ruler commands in person' if self.ruler_on_field else 'under ' + (us.commander or 'no general')}")
        self.b._submit(self._brief)

    def _our_side(self, snap: Any, fld: Field) -> str:
        if fld.att.player and not fld.dfn.player:
            return "att"
        if fld.dfn.player and not fld.att.player:
            return "dfn"
        if fld.dfn.tag and fld.dfn.tag == snap.tag:
            return "dfn"
        return "att"

    def _lang(self) -> str:
        return prompts.LANGUAGE_NAMES.get(self.b.cfg.language, self.b.cfg.language)

    def _difficulty(self) -> dict[str, Any]:
        return DIFF.get(self.b.cfg.difficulty, DIFF["normal"])

    def _setting(self) -> str:
        try:
            return self.b._setting(self.snap)
        except Exception:  # noqa: BLE001 - a missing save must not stop a battle
            return ""

    def _ruler_line(self) -> str:
        snap = self.snap
        ruler = snap.ruler.name if snap and snap.ruler and snap.ruler.name else "the ruler"
        if self.ruler_on_field:
            return (f"{ruler} commands here in person: orders are given from the saddle, and the ruler's own "
                    "life is at stake whenever they ride close to the fighting.")
        us, _ = self.field.sides(self.ours) if self.field else (Side(), Side())
        return (f"{ruler} is not on the field: the orders are the ruler's will, carried to "
                f"{us.commander or 'the officers in charge'} by fast riders - they arrive late and are carried "
                "out by someone else's judgement.")

    def _field_text(self, fld: Field) -> str:
        us, them = fld.sides(self.ours)
        c = fld.census
        ground = ", ".join(x for x in (fld.topography, fld.vegetation, fld.climate) if x)
        lines = [f"- {fld.name or 'battle'} at {fld.place}" + (f" ({fld.province})" if fld.province else "")
                 + f", {fld.date}",
                 f"- ground: {ground or 'open country'}" + ("; a river runs across it" if fld.river else ""),
                 f"- width of the field: {_width_words(fld.frontage, max(us.men or 0, them.men or 0))}"
                 if fld.frontage else "",
                 "- the guns are still at work; the lines have not closed" if fld.bombard else ""]
        for label, side, key in (("OUR SIDE", us, "own"), ("THEIR SIDE", them, "foe")):
            # The game counts each kind's strength; the side's men are shared out by it.
            strength = {k: c.get(f"{key}_{k}", 0) + (c.get(f"ally_{k}", 0) if key == "own" else 0)
                        for k in ("inf", "cav", "art", "aux")}
            whole = sum(strength.values())
            kinds = [f"about {_men(side.total() * v / whole)} {word}" for k, word in
                     (("inf", "foot"), ("cav", "horse"), ("art", "with the guns"), ("aux", "other troops"))
                     if whole > 0 and side.total() and (v := strength[k]) > 0]
            allies = key == "own" and any(c.get(f"ally_{k}", 0) for k in ("inf", "cav", "art", "aux"))
            lines += [
                f"{label}: {side.country or '?'}" + (" (with allies)" if allies else ""),
                f"- commander: {side.commander or 'no general of note'}"
                + (f", {_skill_words(side.mil)}" if side.mil is not None else ""),
                f"- men on the field: {_men(side.total())}; in the fighting line: {_men(side.men)}; "
                f"held back in reserve: {_men(side.reserve)}",
                f"- the line, from their left to their right: left wing {_men(side.left)} "
                f"({_morale_words(side.left_m)}), centre {_men(side.center)} ({_morale_words(side.center_m)}), "
                f"right wing {_men(side.right)} ({_morale_words(side.right_m)})",
                f"- the whole side's heart: {_morale_words(side.morale)}",
                f"- fallen so far: {_men(side.losses)}" + (f"; taken prisoner: {_men(side.prisoners)}"
                                                          if side.prisoners else ""),
                ("- troops: " + ", ".join(kinds)) if kinds else "",
            ]
        if us.dice is not None and them.dice is not None and us.dice != them.dice:
            lines.append("- fortune today: " + ("with us" if us.dice > them.dice else "with them"))
        return "\n".join(x for x in lines if x)

    def _moved(self, fld: Field) -> str:
        old = self.last_beat or self.first
        if old is None:
            return "- (first report)"
        out = []
        for label, a, b in (("ours", old.sides(self.ours)[0], fld.sides(self.ours)[0]),
                            ("theirs", old.sides(self.ours)[1], fld.sides(self.ours)[1])):
            if a.losses is not None and b.losses is not None and b.losses > a.losses:
                out.append(f"- {label}: {_men(b.losses - a.losses)} more have fallen")
            if a.morale is not None and b.morale is not None and abs(b.morale - a.morale) >= 0.05:
                out.append(f"- {label}: heart {'rising' if b.morale > a.morale else 'falling'}, now "
                           f"{_morale_words(b.morale)}")
            if a.reserve and b.reserve is not None and b.reserve < a.reserve * 0.6:
                out.append(f"- {label}: the reserve has been thrown in ({_men(b.reserve)} still held back)")
            for wing in ("left", "center", "right"):
                was, now = getattr(a, wing), getattr(b, wing)
                if was and (now is None or now < was * 0.35):
                    out.append(f"- {label}: the {wing if wing != 'center' else 'centre'} is almost gone")
        hours = max(0, _hours(fld.date) - _hours(old.date))
        out.append(f"- time since then: about {hours // 24} days and {hours % 24} hours")
        return "\n".join(out)

    def _so_far(self) -> str:
        parts = []
        if self.plan:
            parts.append(f"THE RULER'S PLAN: {self.plan.get('summary', '')} (judged {self.plan.get('soundness', 5)}/10; "
                         f"hidden weak point: {self.plan.get('watch', '')})")
        if self.orders:
            parts.append("ORDERS SINCE, AND HOW THEY WENT (in order):\n" + "\n".join(f"- {o}" for o in self.orders[-6:]))
        return "\n".join(parts)

    def _war(self) -> str:
        try:
            return self.b._war_report(self.snap) if self.snap is not None else ""
        except Exception:  # noqa: BLE001
            return ""

    def _ask(self, task: str, schema: dict, name: str, tokens: int, guide: str = "") -> dict[str, Any]:
        """The guide (an editable text, see prompts.EDITABLE) goes in after formatting."""
        task = task.replace("<<GUIDE>>", prompts.text(guide) if guide else "")
        messages = [{"role": "user", "content": task}]
        return self.b.client.complete_json(messages, schema, schema_name=name, temperature=0.85, max_tokens=tokens)

    # -------------------------------------------------------------- briefing
    def _brief(self) -> None:
        session, fld = self.session, self.first
        if session is None or fld is None or not self.live:
            return
        task = BRIEF_TASK.format(style=prompts.text("battle_narrator"), field=self._field_text(fld), setting=self._setting(), war=self._war(),
                                 ruler=self._ruler_line(), lang=self._lang(),
                                 player=prompts.player_block("battles", "narration", "setting", "avoid"))
        try:
            data = self._ask(task, BRIEF_SCHEMA, "votc_battle_brief", 2600, guide="battle_field")
        except AIError as exc:
            self.b.log(f"Battle briefing not written: {exc}")
            data = {"title": self.title, "briefing": self._field_text(fld), "plans": []}
        if session is not self.b.session or not self.live:
            return
        self.title = str(data.get("title") or self.title)[:70]
        self.briefing = str(data.get("briefing") or "").strip()
        self.b._ui("add_line", self.title, self.briefing)
        self.b._ui("add_note", "Give your plan in your own words - where to strike, what to hold, what to keep "
                               "back. It is judged against this field; the game then runs at the slowest speed "
                               "and pauses when the battle needs you.")
        plans = [_short(str(p), 170) for p in (data.get("plans") or []) if str(p).strip()][:3]
        self.b._ui("set_suggestions", plans, "Possible plans")
        self.b._ui("set_hub", [("battle:leave", "⚔  Leave it to the general")])
        self.b._ui("set_close_label", "Leave it to the general")
        self.b._ui("set_busy", "")
        self.waiting = "plan"

    # ---------------------------------------------------------------- orders
    def on_send(self, session: Any, text: str) -> None:
        if session is not self.session or self.waiting not in ("plan", "order"):
            return
        what = "PLAN FOR THE BATTLE" if self.waiting == "plan" else "OWN ORDER AT THIS MOMENT"
        stage = self.waiting
        self.waiting = "judging"
        self.b._ui("add_player", text)
        self.b._ui("set_suggestions", [])
        self.b._ui("set_hub", [])
        self.b._ui("set_busy", "The order goes out…")
        self.b._submit(lambda: self._judge(text, what, stage))

    def _judge(self, order: str, what: str, stage: str) -> None:
        fld = self.field or self.first
        if fld is None or not self.live:
            return
        diff = self._difficulty()
        task = PLAN_TASK.format(style=prompts.text("battle_narrator"), field=self._field_text(fld), setting=self._setting(),
                                so_far=self._so_far(), what=what, order=order.strip()[:800], levers=LEVER_TEXT,
                                ruler=self._ruler_line(), difficulty=prompts.DIFFICULTY.get(self.b.cfg.difficulty, ""),
                                lang=self._lang()) + "\n" + prompts.player_block("battles")
        try:
            data = self._ask(task, PLAN_SCHEMA, "votc_battle_plan", 1800, guide="battle_judge")
        except AIError as exc:
            self.b.log(f"Battle order not judged: {exc}")
            data = {"soundness": 5, "reading": "", "effects": [], "personal_risk": 0,
                    "summary": order[:200], "watch": ""}
        soundness = max(0, min(10, int(data.get("soundness") or 5)))
        effects = self.clamp(data.get("effects") or [], soundness, diff)
        risk = max(0, min(3, int(data.get("personal_risk") or 0))) if self.ruler_on_field else 0
        lines, fate = self._apply(effects, risk)
        summary = str(data.get("summary") or order)[:240]
        if stage == "plan":
            self.plan = {"summary": summary, "soundness": soundness, "watch": str(data.get("watch") or "")[:400]}
            self.orders.append(f"the plan: {summary}")
        else:
            self.orders.append(f"the ruler's own order: {summary} (judged {soundness}/10)")
            self.reveal.append(f"the ruler's own order ({summary}) - carried out; how well it worked must show "
                               f"from the field, judged {soundness}/10{fate}")
        if fate:
            self.orders[-1] += fate
        self.b.log(f"  battle order judged {soundness}/10: {summary}"
                   + (f" - effects: {', '.join(self._describe(e) for e in effects)}" if effects else ""))
        reading = str(data.get("reading") or "").strip()
        if self.session is not None and self.b.session is self.session:
            if reading:
                self.b._ui("add_line", "", reading)
            self.b._ui("add_note", "The game runs again at the slowest speed. The battle will call you back.")
            self.b._ui("set_busy", "")
            self.b._ui("set_close_label", "To the field")
        self._go(lines)

    def leave(self) -> None:
        """No plan: the general fights as he sees fit; the moments still come."""
        if self.waiting in ("plan", "brief"):
            self.orders.append("the ruler gave no plan and left the battle to the general")
        elif self.waiting == "order":
            self.orders.append("the ruler gave no order at that moment")
        self.waiting = ""
        self._go([])

    def _go(self, lines: list[str]) -> None:
        self.waiting = ""
        self.last_beat = self.field or self.last_beat
        self.b.mail.send(lines + ["votc_battle_go = yes"], label="battle:go")
        if self.over:                           # it ended while the ruler was deciding
            self.waiting = "end"
            self.b._submit(self._finish)

    # ----------------------------------------------------------- the effects
    def clamp(self, raw: list[Any], soundness: int, diff: dict[str, Any]) -> list[dict[str, Any]]:
        """What the AI proposes, made to agree with its own judgement and the difficulty."""
        good_room = 3 if soundness >= 9 else 2 if soundness >= 7 else 1 if soundness >= 4 else 0
        out: list[dict[str, Any]] = []
        for e in raw:
            if not isinstance(e, dict):
                continue
            kind, side = str(e.get("kind", "")), str(e.get("side", "ours"))
            up = str(e.get("direction", "up")) != "down"
            level = max(1, min(3, int(e.get("level") or 1)))
            if kind not in LEVERS and kind not in ("shake", "bleed", "rally"):
                continue
            if side not in ("ours", "theirs"):
                continue
            if kind == "rally":
                side, up = "ours", True
            if kind in ("shake", "bleed"):
                up = True
            good = self._good({"kind": kind, "side": side, "up": up})
            if good:
                if good_room <= 0:
                    continue
                good_room -= 1
                level = min(level, diff["up"])
            else:
                level = min(level, diff["down"])
            out.append({"kind": kind, "side": side, "up": up, "level": level})
            if len(out) >= 3:
                break
        if soundness >= 7 and not any(self._good(e) for e in out):
            out.append({"kind": "morale", "side": "ours", "up": True, "level": 1})
        if soundness <= 3 and not any(not self._good(e) for e in out):
            out.append({"kind": "command", "side": "ours", "up": False, "level": min(2, diff["down"])})
        return out

    @staticmethod
    def _good(e: dict[str, Any]) -> bool:
        """Good for the ruler's side."""
        if e["kind"] in ("shake", "bleed"):
            return e["side"] == "theirs"
        if e["kind"] == "rally":
            return True
        return e["up"] == (e["side"] == "ours")

    @staticmethod
    def _describe(e: dict[str, Any]) -> str:
        return f"{e['kind']} {'+' if e['up'] else '-'}{e['level']} ({e['side']})"

    def _apply(self, effects: list[dict[str, Any]], risk: int) -> tuple[list[str], str]:
        """The mail lines for these effects, and what befell the ruler, if anything."""
        lines = []
        for e in effects:
            lv = e["level"]
            if e["kind"] in LEVERS:
                key = modifier_key(e["kind"], e["up"], lv)
                if e["side"] == "ours":
                    lines.append(f"votc_battle_mod = {{ mod = {key} days = {OWN_DAYS} }}")
                else:
                    lines.append(f"votc_battle_foe_mod = {{ mod = {key} days = {FOE_DAYS} }}")
            elif e["kind"] == "shake":
                lines.append(f"votc_battle_shake_{'own' if e['side'] == 'ours' else 'foe'} = {{ p = {SHAKE[lv - 1]} }}")
            elif e["kind"] == "bleed":
                lines.append(f"votc_battle_bleed_{'own' if e['side'] == 'ours' else 'foe'} = {{ p = {BLEED[lv - 1]} }}")
            elif e["kind"] == "rally":
                lines.append(f"votc_battle_rally = {{ p = {RALLY[lv - 1]} }}")
        fate = ""
        if risk and self.ruler_on_field:
            danger = self._difficulty()["risk"]
            roll = random.random()
            if roll < FALL[risk] * danger:
                lines.append("votc_battle_fall_ruler = yes")
                fate = " - AND THE RULER FELL: struck down in the fighting and killed"
            elif roll < (FALL[risk] + WOUND[risk]) * danger:
                lines.append("votc_battle_wound_ruler = yes")
                fate = " - and the ruler was wounded in the fighting (not mortally)"
            if risk >= 2 and "fall" not in fate:
                lines.append(f"votc_battle_rally = {{ p = {RALLY[0]} }}")      # the men saw the ruler among them
        return lines, fate

    # --------------------------------------------------------------- moments
    def _moment_due(self, fld: Field) -> bool:
        if len(self.moments) >= MAX_MOMENTS or self.last_beat is None:
            return False
        hours = _hours(fld.date) - _hours(self.last_beat.date)
        if hours <= 0:
            return False
        us, them = fld.sides(self.ours)
        was_us, was_them = self.last_beat.sides(self.ours)
        big = 0
        for a, b in ((was_us, us), (was_them, them)):
            if a.morale is not None and b.morale is not None and a.morale - b.morale >= 0.15:
                big += 1
            if a.reserve and b.reserve is not None and b.reserve < a.reserve * 0.5:
                big += 1
            for wing in ("left", "center", "right"):
                was, now = getattr(a, wing), getattr(b, wing)
                if was and (now is None or now < was * 0.35):
                    big += 1
            if b.morale is not None and b.morale < 0.25 and (a.morale or 1) >= 0.25:
                big += 2                     # the edge of a rout: the last chance to act
        if not self.moments:
            return hours >= 24 or big >= 1           # the first clash
        if big >= 2:
            return hours >= 6
        if big:
            return hours >= 24
        return hours >= 72                            # a long grind: the battle needs its ruler again

    def _moment(self, fld: Field) -> None:
        if not self.live:
            return
        diff = self._difficulty()
        first = not self.moments
        focus = ("the first clash - the lines meet; how the plan survives contact with the enemy."
                 if first else "the battle has turned a corner since the last report: tell what changed and "
                               "what now hangs in the balance.")
        reveal = ""
        if self.reveal:
            reveal = "HOW THE LAST ORDERS WENT (secret until now - this moment must show it on the field):\n" + \
                     "\n".join(f"- {r}" for r in self.reveal)
        task = MOMENT_TASK.format(
            style=prompts.text("battle_narrator"), hours=fld.date, field=self._field_text(fld), moved=self._moved(fld),
            setting=self._setting(), so_far=self._so_far(), reveal=reveal, focus=focus,
            reveal_rule=("Begin with what came of the last orders, shown not told." if reveal else ""),
            levers=LEVER_TEXT, ruler=self._ruler_line(),
            difficulty=prompts.DIFFICULTY.get(self.b.cfg.difficulty, ""), lang=self._lang(),
            player=prompts.player_block("battles", "narration", "avoid"))
        try:
            data = self._ask(task, MOMENT_SCHEMA, "votc_battle_moment", 3200, guide="battle_moment")
        except AIError as exc:
            self.b.log(f"Battle moment not written: {exc} - the battle runs on.")
            self._go([])
            return
        if self.over:                           # it ended before the moment was written
            self._go([])
            return
        options = [o for o in (data.get("options") or []) if isinstance(o, dict) and str(o.get("label", "")).strip()]
        if len(options) < 3 or not str(data.get("body") or "").strip():
            self.b.log("Battle moment incomplete - the battle runs on.")
            self._go([])
            return
        self.reveal = []
        moment = {"date": fld.date, "title": str(data.get("title") or self.title)[:70],
                  "body": str(data.get("body") or "").strip()[:2400], "options": options[:3], "field": fld}
        self.moments.append(moment)
        loc = {"votc_bt_title": moment["title"], "votc_bt_body": with_gist(data.get("gist"), moment["body"])}
        for i, o in enumerate(moment["options"], 1):
            loc[f"votc_bt_opt{i}"] = str(o.get("label")).strip()[:120]
        self.last_beat = fld
        self.waiting = "choice"
        self.b.mail.send(["votc_battle_moment = yes"], loc=loc, label="battle:moment")
        self.b.log(f"  battle moment: {moment['title']}")
        if self.session is not None and self.b.session is self.session:
            self.b._ui("close")
            self.b.session = None
        self.session = None

    def on_choice(self, n: int) -> None:
        """The player answered a moment of the battle (1-3, or 4: in person)."""
        if not self.live or self.waiting != "choice" or not self.moments:
            return
        moment = self.moments[-1]
        if n == 4:
            self._open_order(moment)
            return
        if not 1 <= n <= len(moment["options"]):
            self.leave()
            return
        opt = moment["options"][n - 1]
        diff = self._difficulty()
        chance = max(5, min(95, int(opt.get("chance") or 50) + diff["luck"]))
        us, _ = (self.field or moment["field"]).sides(self.ours)
        if us.mil is not None:
            mil = us.mil if us.mil > 10 else us.mil * 10
            chance = max(5, min(95, chance + int((mil - 50) / 6)))
        worked = random.random() * 100 < chance
        case = opt.get("success" if worked else "failure") or {}
        soundness = 8 if worked else 2
        effects = self.clamp(case.get("effects") or [], soundness, diff)
        risk = max(0, min(3, int(opt.get("personal_risk") or 0))) if self.ruler_on_field else 0
        lines, fate = self._apply(effects, risk)
        label = str(opt.get("label") or "")
        note = str(case.get("note") or "")
        self.orders.append(f"at '{moment['title']}' the ruler ordered: {label} - it "
                           f"{'worked' if worked else 'went wrong'}: {note}{fate}")
        self.reveal.append(f"'{label}': it {'WORKED' if worked else 'WENT WRONG'} - {note}{fate}")
        self.b.log(f"  battle order: {label} - {'worked' if worked else 'went wrong'} ({chance}%)"
                   + (f"; effects: {', '.join(self._describe(e) for e in effects)}" if effects else "") + fate)
        self._go(lines)

    def _open_order(self, moment: dict[str, Any]) -> None:
        snap = self.snap
        header = Header("Battle", moment["title"], self.title)
        from .app import Session
        self.session = Session(kind="battle", snap=snap, header=header)
        self.b.session = self.session
        self.b._ui("open", header)
        self.b._ui("add_line", moment["title"], moment["body"])
        self.b._ui("add_note", "What do you do? Your own order, in your own words"
                   + (" - you are on the field, and may go where the fighting is." if self.ruler_on_field else
                      " - a rider will carry it to your general."))
        self.b._ui("set_hub", [("battle:leave", "⚔  Leave it to the general")])
        self.b._ui("set_close_label", "Leave it to the general")
        self.waiting = "order"

    # ------------------------------------------------------------------- end
    def _finish(self) -> None:
        """The battle is over: stop the reports, clear the orders, tell how it ended."""
        self.b.mail.send(["votc_battle_end = yes"], label="battle:end")
        last, first = self.field, self.first
        if last is None or first is None:
            self.reset()
            return
        us, them = last.sides(self.ours)
        won = self._we_won(us, them)
        result = ("WE WON: the enemy broke and left the field." if won is True else
                  "WE LOST: our army broke and left the field." if won is False else
                  "It ended without a clear rout - both sides drew apart.")
        reveal = ""
        if self.reveal:
            reveal = "HOW THE LAST ORDERS WENT (secret until now):\n" + "\n".join(f"- {r}" for r in self.reveal)
        task = AFTER_TASK.format(style=prompts.text("battle_narrator"), result=result, first=self._field_text(first),
                                 last=self._field_text(last), so_far=self._so_far(), reveal=reveal,
                                 reveal_rule_short="including how the last orders went" if reveal else "as they were",
                                 lang=self._lang(), player=prompts.player_block("battles", "narration", "avoid"))
        try:
            data = self._ask(task, AFTER_SCHEMA, "votc_battle_after", 3000, guide="battle_end")
        except AIError as exc:
            self.b.log(f"Account of the battle not written: {exc}")
            data = {}
        title = str(data.get("title") or self.title)[:70]
        body = str(data.get("body") or "").strip()[:2600]
        note = str(data.get("memory_note") or "").strip()[:400] or (
            f"{self.title}: {us.country} against {them.country} at {last.place} - "
            + ("victory" if won else "defeat" if won is False else "no clear result")
            + f"; our losses about {_men(us.losses)}, theirs {_men(them.losses)}.")
        mem = self.b.memory
        if mem is not None and body:
            mem.add_page(last.date, "battle", title, body)
        self.b._war_fact(last.date, f"battle: {note}")          # the court's memory and the book of the reign
        if body:
            self.b.last_scene = {"title": title, "body": body, "kind": "battle"}
            self.b.mail.send(["votc_battle_show_end = yes"],
                             loc={"votc_bt_end_title": title, "votc_bt_end_body": with_gist(data.get("gist"), body)},
                             label="battle:after")
        self.b.log(f"Battle over: {note}")
        self.reset()

    @staticmethod
    def _we_won(us: Side, them: Side) -> bool | None:
        a, b = us.morale, them.morale
        if a is None or b is None:
            return None
        if b <= 0.2 and a > b:
            return True
        if a <= 0.2 and b > a:
            return False
        if abs(a - b) < 0.1:
            return None
        return a > b

    # ------------------------------------------------------------- the panel
    def on_close(self, session: Any) -> None:
        if session is not self.session:
            return
        self.session = None
        if self.waiting in ("plan", "order"):
            self.leave()

    def on_hub(self, key: str) -> None:
        if key == "battle:leave":
            self.b._ui("close")
            if self.b.session is self.session:
                self.b.session = None
            self.session = None
            self.leave()
