"""Generate the mod's LIVE picture: the effect that fills the slots and the
bridge lines that report them.

Run from the repository root:  python tools/gen_live.py

Why generated: the localisation templates cannot iterate a list, so every
country the middleware should hear about is parked in its own variable on the
player's country, and every variable needs its own guarded block and its own
line. Thirty near-identical blocks are better written by a loop than by hand.

What it reports, every heartbeat (about every 90 seconds while the game runs)
and whenever the Corte menu opens - without waiting for a save:
  war   countries at war with the player
  ally  allies
  rival rivals (either direction)
  subj  subjects
  lord  the overlord
  gp    the great powers
  near  neighbours
each with its ruler and, if it is at war, its most important enemy. Diffing
two of these pictures is how Court Brain learns that a war broke out, a
ruler died or an alliance ended, long before the next save.
"""

from __future__ import annotations

import io
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MOD = ROOT / "mod" / "WhispersInTheCourt"
EFFECTS = MOD / "in_game" / "common" / "scripted_effects" / "votc_live_effects.txt"
BRIDGE = MOD / "main_menu" / "localization" / "english" / "votc_bridge_l_english.yml"

# name -> (slots, limit on the candidate country; scope:votc_country = player)
LISTS = {
    "war": (4, "is_at_war_with = scope:votc_country"),
    "ally": (4, "is_allied_with = { target = scope:votc_country }"),
    "rival": (3, "OR = { is_rival_of = scope:votc_country scope:votc_country = { is_rival_of = prev } }"),
    "subj": (4, "is_subject_of = scope:votc_country"),
    "lord": (1, "scope:votc_country = { is_subject_of = prev }"),
    "gp": (8, "is_great_power = yes"),
    "near": (6, "is_neighbor_of = scope:votc_country"),
}

# Emits that carry the live picture. Every emit carries the ID line.
LIVE_EMITS = ("pulse", "hub", "advisor")


def slot_names():
    for name, (count, _limit) in LISTS.items():
        for k in range(1, count + 1):
            yield name, k, f"votc_lv_{name}{k}"


def effect_text() -> str:
    out = [
        "﻿# Whispers in the Court - the live picture of the world around the player.",
        "# GENERATED by tools/gen_live.py - edit that, not this.",
        "#",
        "# Every slot is first pointed at the player's own country, which the",
        "# middleware reads as 'empty'; real countries then overwrite it. Each",
        "# position is guarded by a count so the engine never has to cap an",
        "# out-of-range position (which it reports as an error).",
        "",
        "votc_prepare_live = {",
        "\tsave_scope_as = votc_country",
    ]
    for _name, _k, var in slot_names():
        out.append(f"\tset_variable = {{ name = {var} value = scope:votc_country }}")
        out.append(f"\tset_variable = {{ name = {var}_foe value = scope:votc_country }}")
    for name, (count, limit) in LISTS.items():
        base = f"this != scope:votc_country {limit}"
        for k in range(1, count + 1):
            var = f"votc_lv_{name}{k}"
            out += [
                f"\t# {name} #{k}",
                "\tif = {",
                f"\t\tlimit = {{ any_country = {{ count >= {k} {base} }} }}",
                "\t\tordered_country = {",
                f"\t\t\tlimit = {{ {base} }}",
                "\t\t\torder_by = great_power_score",
                f"\t\t\tposition = {k - 1}",
                "\t\t\tcheck_range_bounds = no",
                "\t\t\tsave_scope_as = votc_lv_c",
                f"\t\t\tscope:votc_country = {{ set_variable = {{ name = {var} value = scope:votc_lv_c }} }}",
                f"\t\t\tscope:votc_country = {{ set_variable = {{ name = {var}_foe value = scope:votc_lv_c }} }}",
                "\t\t\tif = {",
                "\t\t\t\tlimit = { any_country = { is_at_war_with = scope:votc_lv_c } }",
                "\t\t\t\tordered_country = {",
                "\t\t\t\t\tlimit = { is_at_war_with = scope:votc_lv_c }",
                "\t\t\t\t\torder_by = great_power_score",
                "\t\t\t\t\tposition = 0",
                "\t\t\t\t\tcheck_range_bounds = no",
                f"\t\t\t\t\tscope:votc_country = {{ set_variable = {{ name = {var}_foe value = prev }} }}",
                "\t\t\t\t}",
                "\t\t\t}",
                "\t\t}",
                "\t}",
            ]
    out += ["}", ""]
    return "\n".join(out)


def live_line(name: str, k: int, var: str) -> str:
    c = f"GetPlayer.MakeScope.GetVariable('{var}').GetCountry"
    f = f"GetPlayer.MakeScope.GetVariable('{var}_foe').GetCountry"
    return (
        f"votc_say LIVE|{name}|{k}|[{c}.GetTag]|[{c}.GetNameWithNoTooltip]"
        f"|[{c}.GetGovernment.GetRuler.GetNameWithNoTooltip]"
        f"|foe=[{f}.GetTag]|foename=[{f}.GetNameWithNoTooltip]"
        f"|army=[{c}.MakeScope.ScriptValue('votc_c_army_size')|0]"
    )


ID_LINE = ("votc_say ID|campaign=[GetPlayer.MakeScope.ScriptValue('votc_v_campaign')|0]"
           "|head=[GetPlayer.MakeScope.ScriptValue('votc_v_memhead')|0]"
           # the number of the last scene of each kind, so that its text can be put back after a load
           + "".join(f"|sc_{k}=[GetPlayer.MakeScope.ScriptValue('votc_v_scene_{k}')|0]"
                     for k in ("out", "chr", "knk", "arc", "obt", "cen", "bt", "bte")))


def patch_bridge() -> None:
    text = io.open(BRIDGE, encoding="utf-8-sig").read()

    def fix(m: re.Match) -> str:
        key, kind, body = m.group(1), m.group(2), m.group(3)
        cmds = [c for c in body.split(";") if not c.startswith(("votc_say ID|", "votc_say LIVE|"))]
        end = next(i for i, c in enumerate(cmds) if c.startswith("votc_say END|"))
        extra = [ID_LINE]
        if kind in LIVE_EMITS:
            extra += [live_line(n, k, v) for n, k, v in slot_names()]
        cmds[end:end] = extra
        return f' {key}:0 "{";".join(cmds)}"'

    text = re.sub(r' (votc_emit_(\w+)):0 "(votc_say SIG\|.*)"', fix, text)
    io.open(BRIDGE, "w", encoding="utf-8-sig", newline="\n").write(text)


if __name__ == "__main__":
    io.open(EFFECTS, "w", encoding="utf-8", newline="\n").write(effect_text())
    patch_bridge()
    print(f"wrote {EFFECTS.name} ({sum(c for c, _ in LISTS.values())} slots) and patched {BRIDGE.name}")
