#!/usr/bin/env python3
"""Generate the mod's side of "Command the battle" (see courtbrain/battle.py).

Writes, from battle.LEVERS so that the two can never disagree:
  main_menu/common/static_modifiers/votc_battle_modifiers.txt   the unit modifiers
  in_game/common/scripted_effects/votc_battle_effects.txt      what a mail may call
  in_game/common/script_values/votc_battle_values.txt          the troops on the field
  main_menu/localization/english/votc_battle_l_english.yml     names and texts
and the bridge's commands in votc_bridge_l_english.yml (the field's report).

    python tools/gen_battle.py
"""

from __future__ import annotations

import io
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MOD = ROOT / "mod" / "WhispersInTheCourt"
sys.path.insert(0, str(ROOT / "tools" / "court_brain"))

from courtbrain.battle import LEVERS, all_modifiers  # noqa: E402

BOM = "﻿"
MODIFIERS = MOD / "main_menu/common/static_modifiers/votc_battle_modifiers.txt"
EFFECTS = MOD / "in_game/common/scripted_effects/votc_battle_effects.txt"
VALUES = MOD / "in_game/common/script_values/votc_battle_values.txt"
LOC = MOD / "main_menu/localization/english/votc_battle_l_english.yml"
BRIDGE = MOD / "main_menu/localization/english/votc_bridge_l_english.yml"
DYNAMIC = MOD / "main_menu/localization/english/votc_dynamic_l_english.yml"

HEAD = "# Whispers in the Court - commanding a battle. GENERATED by tools/gen_battle.py: edit there.\n"


def write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    io.open(path, "w", encoding="utf-8", newline="\n").write(BOM + text)


def fmt(v: float) -> str:
    return (f"{v:.3f}".rstrip("0").rstrip(".")) if isinstance(v, float) else str(v)


# ---------------------------------------------------------------- modifiers
def modifiers_text() -> str:
    out = [HEAD, "# Short, and only while the battle lasts: the ruler's orders, well or badly given.", ""]
    for key, _name, vals in all_modifiers():
        out.append(f"{key} = {{")
        out.append("\tgame_data = { category = unit }")
        for t, v in vals:
            out.append(f"\t{t} = {fmt(v)}")
        out.append("}")
    out += ["", "# The ruler took a wound in the fighting.", "votc_battle_wound = {",
            "\tgame_data = { category = character }", "\tadm = -5", "\tdip = -5", "\tmil = -10", "}", ""]
    return "\n".join(out)


# ------------------------------------------------------------------ effects
KINDS = {
    "inf": ("army_light_infantry", "army_heavy_infantry"),
    "cav": ("army_light_cavalry", "army_heavy_cavalry"),
    "art": ("army_artillery",),
    "aux": ("army_auxiliary",),
}
SIDES = {
    "own": "owner = root",
    "foe": "owner = { is_at_war_with = root }",
    "ally": "NOT = { owner = root } NOT = { owner = { is_at_war_with = root } }",
}


def effects_text() -> str:
    strip = "\n".join(f"\tremove_unit_modifier = {key}" for key, _n, _v in all_modifiers())
    return HEAD + f"""#
# Everything here runs with root = the player's country (a mail, or a console
# command from the bridge). var:votc_bloc is the location of the battle.
# EU5 does not let an effect read back a variable it set a moment ago: every
# flag below is set by one command and read by a later one.

# The player took command (the "Command the battle" button in the battle
# window, or the army's ability): the button already paused the game; the
# bridge runs this as a console command, so that root is the country.
votc_battle_take = {{
	remove_variable = votc_sig_btake
	set_variable = {{ name = votc_bt_live value = 1 }}
	set_variable = {{ name = votc_bt_hold value = 1 }}
	set_variable = {{ name = votc_bt_a value = 1 }}
	votc_prepare_context = yes
	set_variable = {{ name = votc_sig_battle value = 1 }}
}}

# The report loop: each report hands over to the other flag, which starts the
# bridge's next report (see votc_bridge.gui). A kick is the same hand-over.
votc_battle_flip = {{
	if = {{
		limit = {{ has_variable = votc_bt_live NOT = {{ exists = var:votc_bloc }} }}
		remove_variable = votc_bt_live
	}}
	else_if = {{
		limit = {{ has_variable = votc_bt_live }}
		if = {{
			limit = {{ has_variable = votc_bt_a }}
			remove_variable = votc_bt_a
			set_variable = {{ name = votc_bt_b value = 1 }}
		}}
		else = {{
			remove_variable = votc_bt_b
			set_variable = {{ name = votc_bt_a value = 1 }}
		}}
	}}
}}
votc_battle_kick = {{
	votc_battle_flip = yes
}}

# Pause (a moment of the battle is being written) and run again, at speed 1.
votc_battle_hold = {{
	set_variable = {{ name = votc_bt_hold value = 1 }}
}}
votc_battle_go = {{
	remove_variable = votc_bt_hold
	set_variable = {{ name = votc_bt_go value = 1 }}
}}

# The orders, well or badly given: on our men there, or on the enemy's.
votc_battle_mod = {{
	var:votc_bloc ?= {{
		every_unit_in_location = {{
			limit = {{ owner = root in_combat = yes }}
			add_unit_modifier = {{ modifier = $mod$ days = $days$ mode = add_and_extend }}
		}}
	}}
}}
votc_battle_foe_mod = {{
	var:votc_bloc ?= {{
		every_unit_in_location = {{
			limit = {{ owner = {{ is_at_war_with = root }} in_combat = yes }}
			add_unit_modifier = {{ modifier = $mod$ days = $days$ mode = add_and_extend }}
		}}
	}}
}}

# Blows struck at once.
votc_battle_shake_own = {{
	var:votc_bloc ?= {{ every_unit_in_location = {{ limit = {{ owner = root in_combat = yes }} damage_unit_morale_percent = $p$ }} }}
}}
votc_battle_shake_foe = {{
	var:votc_bloc ?= {{ every_unit_in_location = {{ limit = {{ owner = {{ is_at_war_with = root }} in_combat = yes }} damage_unit_morale_percent = $p$ }} }}
}}
votc_battle_bleed_own = {{
	var:votc_bloc ?= {{ every_unit_in_location = {{ limit = {{ owner = root in_combat = yes }} damage_unit_percent = $p$ }} }}
}}
votc_battle_bleed_foe = {{
	var:votc_bloc ?= {{ every_unit_in_location = {{ limit = {{ owner = {{ is_at_war_with = root }} in_combat = yes }} damage_unit_percent = $p$ }} }}
}}
votc_battle_rally = {{
	var:votc_bloc ?= {{ every_unit_in_location = {{ limit = {{ owner = root in_combat = yes }} add_morale = $p$ }} }}
}}

# The ruler rode where the fighting was.
votc_battle_wound_ruler = {{
	ruler ?= {{
		add_character_modifier = {{ modifier = votc_battle_wound years = 3 mode = add_and_extend }}
	}}
}}
votc_battle_fall_ruler = {{
	ruler ?= {{ save_scope_as = votc_fallen }}
	if = {{
		limit = {{ exists = scope:votc_fallen }}
		kill_character = {{ target = scope:votc_fallen reason = combat }}
	}}
}}

# What the player sees.
votc_battle_moment = {{
	trigger_event_non_silently = votc.600
}}
votc_battle_show_end = {{
	trigger_event_non_silently = votc.610
}}

# An answer to a moment of the battle (votc.600): 1-3, or 4 for the ruler's own order.
votc_battle_choose = {{
	set_variable = {{ name = votc_bt_choice value = $n$ }}
	set_variable = {{ name = votc_sig_bchoice value = 1 }}
}}

# The battle is over (or nobody commands it any more): the orders fade with it.
votc_bm_strip = {{
{strip}
}}
votc_battle_end = {{
	every_unit = {{ votc_bm_strip = yes }}
	var:votc_bloc ?= {{
		every_unit_in_location = {{
			limit = {{ NOT = {{ owner = root }} }}
			votc_bm_strip = yes
		}}
	}}
	remove_variable = votc_bt_live
	remove_variable = votc_bt_a
	remove_variable = votc_bt_b
	remove_variable = votc_bt_hold
}}
"""


def values_text() -> str:
    out = [HEAD, "# The troops fighting on the field of var:votc_bloc, by kind and side, as the",
           "# sum of their companies' strength (Court Brain turns it into shares of the",
           "# men each side has there). Evaluated on the player's country.", ""]
    for side, cond in SIDES.items():
        for kind, cats in KINDS.items():
            test = " ".join(f"sub_unit_category = sub_unit_category:{c}" for c in cats)
            if len(cats) > 1:
                test = f"OR = {{ {test} }}"
            out += [f"votc_v_bc_{side}_{kind} = {{",
                    "\tvalue = 0",
                    "\tvar:votc_bloc ?= {",
                    "\t\tevery_unit_in_location = {",
                    f"\t\t\tlimit = {{ {cond} in_combat = yes }}",
                    "\t\t\tevery_sub_unit = {",
                    f"\t\t\t\tlimit = {{ {test} }}",
                    "\t\t\t\tadd = subunit_strength",
                    "\t\t\t}",
                    "\t\t}",
                    "\t}",
                    "}"]
    out += ["votc_v_bt_choice = { value = 0 if = { limit = { has_variable = votc_bt_choice } add = var:votc_bt_choice } round = yes }", ""]
    return "\n".join(out)


# --------------------------------------------------------------------- loc
def loc_text() -> str:
    lines = ["l_english:", "", " # Whispers in the Court - commanding a battle. GENERATED by tools/gen_battle.py.", ""]
    for key, name, _v in all_modifiers():
        lines.append(f' STATIC_MODIFIER_NAME_{key}:0 "{name}"')
        lines.append(f' STATIC_MODIFIER_DESC_{key}:0 "How the ruler\'s orders are working out on this field. It fades when the battle ends."')
        lines.append(f' {key}:0 "{name}"')
    lines += [
        ' STATIC_MODIFIER_NAME_votc_battle_wound:0 "Wounded in Battle"',
        ' STATIC_MODIFIER_DESC_votc_battle_wound:0 "A wound taken leading the army in person. It heals slowly."',
        ' votc_battle_wound:0 "Wounded in Battle"',
        "",
        ' VOTC_BATTLE_BUTTON:0 "Command"',
        ' VOTC_BATTLE_BUTTON_TT:0 "#T Command the battle#!\\nTake command of this battle through Whispers in the Court: the game pauses, a narrator sets the field before you, and you give your plan in your own words. The battle then runs at the slowest speed and calls you back at the moments that matter."',
        ' votc_take_command:0 "Command the Battle"',
        ' votc_take_command_desc:0 "Take command of this battle through Whispers in the Court: the game pauses, a narrator sets the field before you, and you give your plan in your own words."',
        ' votc_take_command_cta:0 "Click to take command of the battle."',
        "",
        ' votc_bt_opt_self:0 "I will see to this myself."',
        ' votc_bt_self_tt:0 "Give your own order, in your own words, in the court panel."',
        ' votc_bt_hidden_tt:0 "How it goes will show on the field."',
        ' votc_bt_end_ok:0 "So it was."',
        "",
    ]
    return "\n".join(lines)


# ------------------------------------------------------------------ bridge
# EVERY read of the combat must be guarded by HasCombat on the location, as the
# game's own interface does: reading a combat that has ended crashes the game.
# The bridge chooses between the key below and its "gone" twin with
# Select_CString, so the guarded key is never even localised without a combat.
LOCN = "GetPlayer.MakeScope.GetVariable('votc_bloc').GetLocation"
C = LOCN + ".GetCombat"
HAS = LOCN + ".HasCombat"


def _yes(expr: str) -> str:
    return f"[Select_CString({expr}, '1', '0')]"


def battle_lines() -> list[str]:
    lines = [
        "votc_say BATTLE"
        f"|name=[{C}.GetNameWithNoTooltip]|date=[GetDateString]|active={_yes(C + '.IsActive')}"
        f"|naval={_yes(C + '.IsNavalCombat')}|bombard={_yes(C + '.IsInBombardPhase')}"
        f"|frontage=[{LOCN}.GetModifierValue('local_frontage_allowed')]"
        f"|loc=[{LOCN}.GetNameWithNoTooltip]|province=[{LOCN}.GetProvince.GetNameWithNoTooltip]"
        f"|topo=[{LOCN}.GetTopography.GetNameWithNoTooltip]"
        f"|veg=[{LOCN}.GetVegetation.GetNameWithNoTooltip]"
        f"|climate=[{LOCN}.GetClimate.GetNameWithNoTooltip]|river={_yes(LOCN + '.HasRiver')}"
        f"|owner=[{LOCN}.GetOwner.GetNameWithNoTooltip]"]
    for key, getter in (("att", "GetAttacker"), ("def", "GetDefender")):
        s = f"{C}.{getter}"
        lines.append(
            f"votc_say BSIDE|{key}|tag=[{s}.GetCountry.GetTag]|country=[{s}.GetCountry.GetNameWithNoTooltip]"
            f"|player={_yes(s + '.IsPlayerInCombat')}|cmd=[{s}.GetCommander.GetNameWithNoTooltip]"
            f"|mil=[{s}.GetCommander.GetAbility('mil')]|morale=[{s}.GetMoralePercent]"
            f"|men=[{s}.GetEngagedUnitsStrength]|all=[{s}.GetVisualStrength]"
            f"|losses=[{s}.GetBattleSide.GetLosses]|prisoners=[{s}.GetBattleSide.GetTotalImprisoned]"
            f"|dice=[{s}.GetDiceWithModifiers]"
            f"|left=[{s}.GetLeft.GetEngagedStrength]|leftm=[{s}.GetLeft.GetMoralePercentage]"
            f"|center=[{s}.GetCenter.GetEngagedStrength]|centerm=[{s}.GetCenter.GetMoralePercentage]"
            f"|right=[{s}.GetRight.GetEngagedStrength]|rightm=[{s}.GetRight.GetMoralePercentage]"
            f"|reserve=[{s}.GetReserves.GetNonEngagedStrength]")
    census = "|".join(f"{side}_{kind}=[GetPlayer.MakeScope.ScriptValue('votc_v_bc_{side}_{kind}')|2]"
                      for side in SIDES for kind in KINDS)
    lines.append("votc_say BCENSUS|" + census)
    return lines


def patch_bridge() -> None:
    text = io.open(BRIDGE, encoding="utf-8-sig").read()
    hub = re.search(r' votc_emit_hub:0 "(votc_say SIG\|hub\|.*)"', text).group(1)
    cmds = hub.split(";")
    cmds[0] = cmds[0].replace("SIG|hub", "SIG|battle")
    end = next(i for i, c in enumerate(cmds) if c.startswith("votc_say END|"))
    realm = cmds[:end]                              # the picture of the realm, as the hub sends it
    gone = ["votc_say BATTLE|gone=1|date=[GetDateString]"]
    cmds = realm + battle_lines() + ["votc_say END|battle", "effect remove_variable = votc_sig_battle"]
    cmds_gone = realm + gone + ["votc_say END|battle", "effect remove_variable = votc_sig_battle"]
    new = {
        "votc_emit_battle": ";".join(cmds),
        "votc_emit_battle_gone": ";".join(cmds_gone),
        "votc_emit_bgone": ";".join(gone + ["votc_say END|bstate", "effect votc_battle_flip = yes", "run votc_poll.txt"]),
        "votc_emit_bstate": ";".join(battle_lines() + ["votc_say END|bstate", "effect votc_battle_flip = yes",
                                                        "run votc_poll.txt"]),
        "votc_emit_bchoice": ("votc_say BCHOICE|n=[GetPlayer.MakeScope.ScriptValue('votc_v_bt_choice')|0];"
                              "effect remove_variable = votc_sig_bchoice"),
        "votc_cmd_btake": "effect votc_battle_take = yes",
        "votc_cmd_bgo_done": "effect remove_variable = votc_bt_go",
    }
    for key, value in new.items():
        line = f' {key}:0 "{value}"'
        pat = re.compile(rf"^ {key}:0 \".*\"$", re.M)
        if pat.search(text):
            text = pat.sub(lambda _m: line, text)
        else:
            text = text.rstrip("\n") + "\n" + line + "\n"
    io.open(BRIDGE, "w", encoding="utf-8-sig", newline="\n").write(text)


def patch_dynamic() -> None:
    text = io.open(DYNAMIC, encoding="utf-8-sig").read()
    wanted = {
        "votc_bt_title": "The Battle",
        "votc_bt_body": "The battle goes on.",
        "votc_bt_opt1": "Hold the line.",
        "votc_bt_opt2": "Commit the reserve.",
        "votc_bt_opt3": "Send the horse around their flank.",
        "votc_bt_end_title": "After the Battle",
        "votc_bt_end_body": "The field is quiet.",
    }
    for key, value in wanted.items():
        if not re.search(rf"^ {key}:0 ", text, re.M):
            text = text.rstrip("\n") + f'\n {key}:0 "{value}"\n'
    io.open(DYNAMIC, "w", encoding="utf-8-sig", newline="\n").write(text)


if __name__ == "__main__":
    write(MODIFIERS, modifiers_text())
    write(EFFECTS, effects_text())
    write(VALUES, values_text())
    write(LOC, loc_text())
    patch_bridge()
    patch_dynamic()
    print(f"{sum(1 for _ in all_modifiers())} modifiers, {len(LEVERS)} levers; effects, values, loc and bridge written.")
