"""Generate the mod's consequence QUEUE from the middleware's catalogue.

Run from the repository root:  python tools/gen_queue.py

Court Brain no longer applies consequences the moment a conversation ends.
It parks each one in a numbered slot (votc_queue = { slot id }), and the
confirming option of the outcome event applies them (votc_apply_queue).
Because the effects run inside the option, the game's own tooltip on that
button lists exactly what will change - stability, gold, estate
satisfaction, modifiers and how long they last - which is the proof that a
consequence really reached the game.

The numbering comes from courtbrain.actions.variants(), so this file must be
regenerated whenever the catalogue changes.
"""

from __future__ import annotations

import io
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "tools" / "court_brain"))
from courtbrain import actions as A  # noqa: E402

OUT = ROOT / "mod" / "WhispersInTheCourt" / "in_game" / "common" / "scripted_effects" / "votc_queue_effects.txt"


def text() -> str:
    table = A.variants()
    out = [
        "﻿# Whispers in the Court - the consequence queue.",
        "# GENERATED by tools/gen_queue.py from courtbrain/actions.py - do not edit.",
        "#",
        f"# {len(table)} consequences, {A.QUEUE_SLOTS} slots. The run file writes the slots;",
        "# the confirming option of the event applies them, so its tooltip shows them.",
        "",
        "votc_queue = {",
        "\tset_variable = { name = votc_q$slot$ value = $id$ }",
        "}",
        "",
        "# The years of a policy whose duration travels with it (the areas added later:",
        "# their consequence reads var:votc_qy<slot>).",
        "votc_queue_years = {",
        "\tset_variable = { name = votc_qy$slot$ value = $years$ }",
        "}",
        "",
        "votc_queue_clear = {",
    ]
    out += [f"\tremove_variable = votc_q{n}" for n in range(1, A.QUEUE_SLOTS + 1)]
    out += ["}", "", "votc_queue_clear_options = {"]
    out += [f"\tremove_variable = votc_qo{o}_{n}" for o in range(1, A.OPTION_COUNT + 1)
            for n in range(1, A.OPTION_SLOTS + 1)]
    out += ["}", "", "votc_queue_clear_chronicle = {"]
    out += [f"\tremove_variable = votc_qc{n}" for n in range(1, A.QUEUE_SLOTS + 1)]
    out += ["}", "", "# A page of chronicle waits a day on the calendar: its consequences have",
            "# slots of their own, so an outcome in the meantime cannot overwrite them.",
            "votc_apply_chronicle = {"]
    out += [f"\tvotc_apply_slot = {{ slot = c{n} }}" for n in range(1, A.QUEUE_SLOTS + 1)]
    out += ["\tvotc_queue_clear_chronicle = yes", "}", "", "# The option chosen in a story event: its own consequences only.",
            "votc_apply_option = {"]
    out += [f"\tvotc_apply_slot = {{ slot = o$o$_{n} }}" for n in range(1, A.OPTION_SLOTS + 1)]
    out += ["\tvotc_queue_clear_options = yes", "}", "", "votc_apply_queue = {"]
    out += [f"\tvotc_apply_slot = {{ slot = {n} }}" for n in range(1, A.QUEUE_SLOTS + 1)]
    out += ["\tvotc_queue_clear = yes", "}", "", "votc_apply_slot = {", "\tif = {",
            "\t\tlimit = { has_variable = votc_q$slot$ }"]
    for i, (key, line) in enumerate(table, start=1):
        kw = "if" if i == 1 else "else_if"
        out.append(f"\t\t{kw} = {{ limit = {{ var:votc_q$slot$ = {i} }} {line} }}  # {' '.join(key[1:])}")
    out += ["\t}", "}", ""]
    return "\n".join(out)


if __name__ == "__main__":
    io.open(OUT, "w", encoding="utf-8", newline="\n").write(text())
    print(f"wrote {OUT.name}: {len(A.variants())} consequences")
