"""Generate the STANDING MEASURES: policies a ruler keeps in force until they revoke them.

Run from the repository root:  python tools/gen_standing.py

A policy (tools/gen_policies.py) lasts some years. A standing measure - a literacy drive,
a permanent market watch, a new levy on salt - lasts until the ruler ends it, and is paid
for as long as it stands:

  * its GAIN: one lever of the state, at the same strengths as a policy (plus "learning",
    the realm's literacy, and "revenue", a new levy);
  * its PRICE: a share of the Crown's tax income, every month (tax_income_efficiency, as the
    game's own advances use it) - so it grows as the realm grows, and shows in the budget;
  * its BURDEN, when it really weighs on something besides money: a lever pushed the other
    way (the same values as a policy's penalty).

Four slots, so that each measure can be revoked on its own. Each slot's name is a key of
the dynamic text (votc_st<slot>_name), which Court Brain fills with the measure's name.

Writes:
  mod/.../main_menu/common/static_modifiers/votc_standing.txt
  mod/.../main_menu/localization/english/votc_standing_l_english.yml
  mod/.../in_game/common/scripted_effects/votc_standing_effects.txt
"""

from __future__ import annotations

import importlib.util
import io
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MOD = ROOT / "mod" / "WhispersInTheCourt"
MODIFIERS = MOD / "main_menu" / "common" / "static_modifiers" / "votc_standing.txt"
LOC = MOD / "main_menu" / "localization" / "english" / "votc_standing_l_english.yml"
EFFECTS = MOD / "in_game" / "common" / "scripted_effects" / "votc_standing_effects.txt"

spec = importlib.util.spec_from_file_location("gen_policies", ROOT / "tools" / "gen_policies.py")
pol = importlib.util.module_from_spec(spec)
spec.loader.exec_module(pol)

SLOTS = 4
TIERS = pol.TIERS                         # weak 1, mild 2, severe 3
TIER_EN = pol.TIER_EN
# What only a standing measure can move (the rest are the policy areas, learning among them).
EXTRA_GAINS = {
    "revenue": ("A new levy", "a new tax or due: more tax income",
                [("tax_income_efficiency", 0.03)]),       # 3 / 6 / 9% (measures.REVENUE_PCT)
}
GAINS = {**pol.ALL_AREAS, **EXTRA_GAINS}
BURDENS = dict(pol.ALL_AREAS)
# The price: a share of the tax income, every month, for as long as it stands.
COST = {"weak": 0.03, "mild": 0.06, "severe": 0.10}


def _fmt(v: float) -> str:
    return pol._fmt(v)


def modifiers_text() -> str:
    out = ["﻿# Whispers in the Court - STANDING MEASURES. GENERATED by tools/gen_standing.py: edit that.",
           "#", "# votc_st<slot>_gain_<area>_<tier>, votc_st<slot>_cost_<tier>, votc_st<slot>_burden_<area>_<tier>:",
           "# added for good (days = -1) by votc_standing_effects.txt, removed when the ruler ends it.", ""]
    for slot in range(1, SLOTS + 1):
        for area, (_n, _note, keys) in GAINS.items():
            for tier, mult in TIERS.items():
                out += [f"votc_st{slot}_gain_{area}_{tier} = {{", "\tgame_data = { category = country }"]
                out += [f"\t{key} = {_fmt(weak * mult)}" for key, weak in keys] + ["}"]
        for tier, share in COST.items():
            out += [f"votc_st{slot}_cost_{tier} = {{", "\tgame_data = { category = country }",
                    f"\ttax_income_efficiency = {_fmt(-share)}", "}"]
        for area, (_n, _note, keys) in BURDENS.items():
            for tier, mult in TIERS.items():
                out += [f"votc_st{slot}_burden_{area}_{tier} = {{", "\tgame_data = { category = country }"]
                out += [f"\t{key} = {_fmt(-weak * mult)}" for key, weak in keys] + ["}"]
        out.append("")
    return "\n".join(out) + "\n"


def loc_text() -> str:
    out = ["﻿l_english:", ""]
    for slot in range(1, SLOTS + 1):
        name = f"$votc_st{slot}_name$"
        for area, (label, _note, _keys) in GAINS.items():
            for tier in TIERS:
                out.append(f' STATIC_MODIFIER_NAME_votc_st{slot}_gain_{area}_{tier}:0 "{name}: {label.lower()} '
                           f'({TIER_EN[tier]})"')
                out.append(f' STATIC_MODIFIER_DESC_votc_st{slot}_gain_{area}_{tier}:0 "A standing measure of the '
                           f'Crown, in force until the ruler revokes it at court (Whispers in the Court)."')
        for tier, share in COST.items():
            pct = int(round(share * 100))
            out.append(f' STATIC_MODIFIER_NAME_votc_st{slot}_cost_{tier}:0 "{name}: its cost ({pct}% of the tax '
                       f'income)"')
            out.append(f' STATIC_MODIFIER_DESC_votc_st{slot}_cost_{tier}:0 "Paid every month out of the Crown\'s '
                       f'taxes for as long as the measure stands: it grows with the realm. Revoke the measure at '
                       f'court to stop paying (Whispers in the Court)."')
        for area, (label, _note, _keys) in BURDENS.items():
            for tier in TIERS:
                out.append(f' STATIC_MODIFIER_NAME_votc_st{slot}_burden_{area}_{tier}:0 "{name}: its burden on '
                           f'{label.lower()} ({TIER_EN[tier]})"')
                out.append(f' STATIC_MODIFIER_DESC_votc_st{slot}_burden_{area}_{tier}:0 "What the measure weighs '
                           f'on, besides money, for as long as it stands (Whispers in the Court)."')
    return "\n".join(out) + "\n"


def effects_text() -> str:
    out = ["﻿# Whispers in the Court - STANDING MEASURES. GENERATED by tools/gen_standing.py: edit that.",
           "# Court Brain sends: votc_standing_clear_<slot> = yes, then the pieces of the new measure.", "",
           "votc_standing_gain = {",
           "\tadd_country_modifier = { modifier = votc_st$slot$_gain_$area$_$tier$ days = -1 mode = add_and_extend }",
           "\tset_variable = { name = votc_st$slot$ value = 1 }", "}", "",
           "votc_standing_cost = {",
           "\tadd_country_modifier = { modifier = votc_st$slot$_cost_$tier$ days = -1 mode = add_and_extend }",
           "\tset_variable = { name = votc_st$slot$ value = 1 }", "}", "",
           "votc_standing_burden = {",
           "\tadd_country_modifier = { modifier = votc_st$slot$_burden_$area$_$tier$ days = -1 mode = add_and_extend }",
           "}", ""]
    for slot in range(1, SLOTS + 1):
        out.append(f"votc_standing_clear_{slot} = {{")
        for area in GAINS:
            for tier in TIERS:
                out.append(f"\tremove_country_modifier = votc_st{slot}_gain_{area}_{tier}")
        for tier in COST:
            out.append(f"\tremove_country_modifier = votc_st{slot}_cost_{tier}")
        for area in BURDENS:
            for tier in TIERS:
                out.append(f"\tremove_country_modifier = votc_st{slot}_burden_{area}_{tier}")
        out += [f"\tremove_variable = votc_st{slot}", "}", ""]
    return "\n".join(out)


if __name__ == "__main__":
    io.open(MODIFIERS, "w", encoding="utf-8", newline="\n").write(modifiers_text())
    io.open(LOC, "w", encoding="utf-8", newline="\n").write(loc_text())
    io.open(EFFECTS, "w", encoding="utf-8", newline="\n").write(effects_text())
    n = SLOTS * (len(GAINS) * 3 + len(COST) + len(BURDENS) * 3)
    print(f"wrote {n} standing-measure modifiers in {SLOTS} slots")
